---

- name: Gather OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"

- name: verify that X server exists
  stat:
    path: "{{ XGUI.xsession_path }}"
  register: xsession

- name: verify that xterm session exists
  stat:
    path: "{{ XGUI.xterm_path }}"
  register: xterm

- name: set flag for GUI systems
  set_fact:
    has_gui: "{{ xsession.stat.exists and xterm.stat.exists }}"

- name: kill all running vncserver sessions
  command: >
    /bin/su {{ ATMOUSERNAME }} -c "/usr/bin/vncserver -kill :'{{ item }}'"
  with_items: [1, 2, 3, 4, 5, 6, 7, 8]
  failed_when: False

- name: start vncservers and novnc
  shell: "{{ item }}"
  with_items: "{{ VNC_COMMANDS }}"
  when: has_gui
  ignore_errors: yes
  failed_when: False
